name: Deploy lumberchunker to GitHub Pages
on:
  push:
    branches: [ main ]  # deploy whenever main updates

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Upload EXACTLY the subfolder; nothing else is published
      - uses: actions/upload-pages-artifact@v3
        with:
          path: projects/lumberchunker

      - id: deployment
        uses: actions/deploy-pages@v4
